webapp:
  build: ./docker-mold-webapp
  dockerfile: Dockerfile.debug
  environment:
    - HOST_NAME=localhost
    - HOST_PORT=8080
    - BRANCH=master
  ports:
   - "8080:80"
  links:
    - api
    - vt
api:
  build: ./docker-mold-api
  dockerfile: Dockerfile.debug
  environment:
    - BRANCH=sparql_post
  links:
    - vt
vt:
  image: mold/docker-virtuoso
  volumes:
    - ./mold-virtuoso:/mnt/graphs
  ports:
    - "9000:9000"
