webapp:
  image: mold/mold_webapp
  environment:
    - HOST_NAME=localhost
    - HOST_PORT=80
  ports:
   - "80:80"
  links:
   - api
   - vt
api:
  image: mold/mold_api
  links:
    - vt
vt:
  image: zorino/docker-virtuoso
  volumes:
    - ./mold-virtuoso:/mnt/graphs
